refactor: f2elint

diff --git a/.github/workflows/preview-deploy.yml b/.github/workflows/preview-deploy.yml
--- a/.github/workflows/preview-deploy.yml
+++ b/.github/workflows/preview-deploy.yml
@@ -121,7 +121,7 @@ jobs:
 
       - name: Check surge deploy result and exit if failed
         run: |
-            if [ "${{ steps.deploy.outcome }}" != "success" ]; then
-              echo "Surge Deploy failed."
-              exit 1
-            fi
+          if [ "${{ steps.deploy.outcome }}" != "success" ]; then
+            echo "Surge Deploy failed."
+            exit 1
+          fi
